### ISSUE TITLE
jaxb-jxc not compiling in Eclipse

### ISSUE THREAD

**Issue by phax** [gf-metro/jaxb#12]
The pom.xml of the jaxb-jxc 2.2.12-SNAPSHOT is missing a dependency to Ant.
Adding
```xml
        <dependency>
            <groupId>org.apache.ant</groupId>
            <artifactId>ant</artifactId>
        </dependency>        
```
solved the problem for me.
Afterwards compilation in Eclipse with m2e works for me on this project.

**Comment by yaroska** [comment]
This is not correct.

jxc depennds on xjc module. Which has denendency on ant.

[INFO] org.glassfish.jaxb:jaxb-jxc:jar:2.2.12-SNAPSHOT
[INFO] +- org.glassfish.jaxb:jaxb-xjc:jar:2.2.12-SNAPSHOT:compile
[INFO] |  +- (org.glassfish.jaxb:jaxb-core:jar:2.2.12-SNAPSHOT:compile - omitted for duplicate)
[INFO] |  +- com.sun.xsom:xsom:jar:20140925:compile
[INFO] |  |  \- relaxngDatatype:relaxngDatatype:jar:20020414:compile
[INFO] |  +- org.glassfish.jaxb:codemodel:jar:2.2.12-SNAPSHOT:compile
[INFO] |  +- com.sun.xml.bind.external:rngom:jar:2.2.12-SNAPSHOT:compile
[INFO] |  |  \- (relaxngDatatype:relaxngDatatype:jar:20020414:compile - omitted for duplicate)
[INFO] |  +- com.sun.xml.dtd-parser:dtd-parser:jar:1.1:compile
[INFO] |  \- com.sun.istack:istack-commons-tools:jar:2.21:compile
[INFO] |     +- org.apache.ant:ant:jar:1.9.0:compile (version managed from 1.7.0)
[INFO] |     |  \- org.apache.ant:ant-launcher:jar:1.9.0:compile
[INFO] |     \- (com.sun:tools:jar:1.6:system - omitted for duplicate)

**Comment by phax** [comment]
There seems to be a difference between the command line Maven and m2e, because ant is using the "provided" scope. Removing the explicit scope fixes the issue - maybe you can think this through...

**Comment by phax** [comment]
So I assume you are not fixing this issue - right?

**Comment by yaroska** [comment]
To be honest, I don't see the issue. 

Provided scope for Ant is used because it's expected that JAXB Ant tasks to be run within Ant. So this dependency will be available at runtime.

**Comment by phax** [comment]
My proposed fix would just be a sanity handling for all Eclipse users. Add "ant" with a "provided" scope in "xjc" and I'm happy :)

**Comment by yaroska** [comment]
You are right. According to the Maven spec "provided" scope is not transitive. But as you see from the dependency tree JXC gets Ant dependency through XJC -> istack-commons-tools, not from XJC explicitly.

**Comment by yaroska** [comment]
I think it would be more correct to open bug against m2e. I hope you agree that in this case dependency should be resolved. Even if in XJC Ant is specified as 'provided'. 

What do you think about adding Ant as JXC 'provided' dependency ?

**Comment by phax** [comment]
No I think this is a bug in the commandline Maven, because the "provided" dependency is passed on even though it should not :) So the bug should be filed to Maven to either update the specs or fix it. I'm using Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00) - what is your version?

**Comment by phax** [comment]
Adding ant as provided would be fine for me!

Am 1. April 2015 18:54:36 MESZ, schrieb Iaroslav Savytskyi <notifications@github.com>:
>I think it would be more correct to open bug against m2e. I hope you
>agree that in this case dependency should be resolved. Even if in XJC
>Ant is specified as 'provided'. 
>
>What do you think about adding Ant as JXC 'provided' dependency ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gf-metro/jaxb/issues/12#issuecomment-88539271

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by yaroska** [comment]
Fixed in trunk.
